# Generated by Django 4.1.13 on 2024-10-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_chaises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_chaises/'),
        ),
    ]
